### ISSUE TITLE
Protecting files

### ISSUE THREAD

**Issue by mikelitu** [KCL-BMEIS/KCL-DGX-cluster-documentation#9]
A short tutorial on how to protect your files and change permissions for the rest of the users of DGX to not have access. I had a discussion with a student on how to secure clinical data on the cluster, as this could be a big concern. By default, all the data repositories have default permissins so you need to change permissions on your files to hide them from the rest of the users. I will write some information on how to work on this.

**Comment by pwrightkcl** [comment]
I think this comes under a related change we've asked the admins to make. We want people to store data in project directories and keep their home directories for low-volume personal files (configs etc.). Project directories would be access controlled via Linux group. The admin would set that up. You can see existing access-restricted project directories using `ls -l /nfs/project` and noting those with `drwxrws---` permissions, like `MIDI`, `mirada`, `NeuroRadKCH` etc.

I don't think there's scope for a tutorial here, because only admins can create groups. The limit would be changing your home directory to `drwx------`, which we could do.

I was thinking of expanding the use guidelines from only GPU to cover CPU, storage, and IO. That could include "security" and mention the above.
